---
- name: Health check nodes
  hosts: all
  gather_facts: false

  tasks:
    - name: Curl node http (expect 404)
      delegate_to: localhost
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}/demo"
        method: GET
        status_code: 404
