---
- name: Setup web server on node1
  hosts: node1.example.com
  gather_facts: false
  become: true

  tasks:
    - name: Install httpd
      ansible.builtin.package:
        name:
          - httpd
          - firewalld
        state: present

    - name: Start service
      ansible.builtin.service:
        name:
          - httpd
          - firewalld
        state: started

    - name: Open firewall port
      ansible.builtin.firewalld:
        port: 80/tcp
        state: enabled
