---
- name: Setup web server on node1
  hosts: node1.example.com
  gather_facts: false
  become: true

  tasks:
    - name: Install httpd
      ansible.builtin.package:
        name:
          - httpd
          - firewalld
        state: present

    - name: Start service
      loop:
        - httpd
        - firewalld
      ansible.builtin.service:
        name: "{{ item }}"
        state: started

    - name: Open http firewall port
      ansible.builtin.firewalld:
        port: 80/tcp
        state: enabled

    - name: Open ssh firewall port
      ansible.builtin.firewalld:
        port: 22/tcp
        state: enabled
