---
- name: Setup web server on node1
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - httpd
          - firewalld
        state: present

    - name: Start services
      loop:
        - httpd
        - firewalld
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true

    - name: Open http firewall port
      ansible.builtin.firewalld:
        port: 80/tcp
        state: enabled
        permanent: true

    - name: Open ssh firewall port
      ansible.builtin.firewalld:
        port: 22/tcp
        state: enabled
        permanent: true
