---
- name: Custom slack notification for patching updates
  hosts: localhost

  tasks:
    - name: Check for stats
      block:
        - name: Assert stats passed from vlan playbook
          ansible.builtin.assert:
            that: nodes_updated is defined
      rescue:
        - name: Set default value
          ansible.builtin.set_fact:
            nodes_updated: []

    - name: Debug set stats
      ansible.builtin.debug:
        var: nodes_updated

    - name: Post diff to slack
      loop: "{{ nodes_updated }}"
      loop_control:
        loop_var: node
      ansible.builtin.uri:
        url: https://slack.com/api/files.upload
        method: POST
        headers:
          Authorization: "Bearer {{ slack_token }}"
        body_format: form-urlencoded
        body:
          content: "{{ node.updates | to_nice_yaml }}"
          title: "Patching Updates for {{ node.hostname }}"
          channels: "smart-mgmt-demo"
